name: 'Mirror To Gitee'

on: [push, delete]

jobs:
  mirror_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@master
        with: 
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: 'mirror to gitee'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitee.com:icarusky/Icarusky.git
          ssh_private_key:
            ${{ secrets.GITEE_PRIVATE_KEY }}
